# Generated by Django 5.2.4 on 2025-07-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_user_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
